from turtle_curve.generator import FractionGenerator


def test_fraction_generator():
	'''Test the fractions generated by the fraction generator'''
	assert ''.join([str(d) for d in FractionGenerator(19, max_iter=40)]) == '0052631578947368421052631578947368421052'